CREATE DATABASE VOTER_PROJECT;

USE VOTER_PROJECT;

CREATE TABLE VOTER_TABLE(
VOTER_ID VARCHAR(50) PRIMARY KEY,
NAME VARCHAR(50),
DATE_OF_BIRTH DATE,
CONSTITUENCY VARCHAR(20),
POLLING_BOOTH VARCHAR(20),
VOTING_STATUS INT)

CREATE TABLE CANDIDATE_TABLE(
NAME VARCHAR(50),
CONSTITUENCY VARCHAR(20) PRIMARY KEY,
PARTY VARCHAR(50),
VOTE_COUNT INT)

CREATE TABLE PARTY_TABLE(
NAME VARCHAR(50),
CONSTITUENCY VARCHAR(20) PRIMARY KEY,
LOGO VARCHAR(50),
VOTE_COUNT INT)

CREATE TABLE CONSTITUENCY_TABLE(
CONSTITUENCY VARCHAR(20) PRIMARY KEY,
DISTRICT VARCHAR(20),
STATE VARCHAR(20))

CREATE TABLE VOTING_DAY_TABLE(
CONSTITUENCY VARCHAR(20),
CANDIDATE_NAME VARCHAR(20))

CREATE TABLE PASSPORT_VERIFICATION_TABLE(
	PASSPORT_NUM VARCHAR(20) PRIMARY KEY,
	NAME_NRI VARCHAR(40),
	COUNTRY_OF_RESIDENCE VARCHAR(20)

);

--ALTER TABLE CANDIDATE_TABLE ADD PARTY VARCHAR(50);
ALTER TABLE CANDIDATE_TABLE ADD CANDIDATE_ID VARCHAR(50) UNIQUE;

SELECT * FROM CANDIDATE_TABLE

SELECT * FROM VOTER_TABLE;

SELECT * FROM PARTY_TABLE;


SELECT * FROM VOTING_DAY_TABLE
